// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package conversationdb

import (
	"database/sql"
)

type Blob struct {
	Sha256      []byte `json:"sha256"`
	Data        []byte `json:"data"`
	CreatedAtMs int64  `json:"created_at_ms"`
}

type Conversation struct {
	ID               string `json:"id"`
	Platform         string `json:"platform"`
	AccountID        string `json:"account_id"`
	ExternalChatID   string `json:"external_chat_id"`
	ExternalThreadID string `json:"external_thread_id"`
	NextHistorySeq   int64  `json:"next_history_seq"`
	CreatedAtMs      int64  `json:"created_at_ms"`
	UpdatedAtMs      int64  `json:"updated_at_ms"`
}

type Message struct {
	RecordID       string         `json:"record_id"`
	ConversationID string         `json:"conversation_id"`
	RunID          string         `json:"run_id"`
	SourceRecordID sql.NullString `json:"source_record_id"`
	Role           string         `json:"role"`
	HistorySeq     sql.NullInt64  `json:"history_seq"`
	StepSeq        sql.NullInt64  `json:"step_seq"`
	StepMessageSeq sql.NullInt64  `json:"step_message_seq"`
	CommittedAtMs  sql.NullInt64  `json:"committed_at_ms"`
}

type Outbox struct {
	ID              string         `json:"id"`
	RecordID        string         `json:"record_id"`
	EnqueueSeq      int64          `json:"enqueue_seq"`
	ConversationID  string         `json:"conversation_id"`
	RunID           string         `json:"run_id"`
	MessageRecordID sql.NullString `json:"message_record_id"`
	ReplyToRecordID sql.NullString `json:"reply_to_record_id"`
	Kind            string         `json:"kind"`
	ChunkIndex      int64          `json:"chunk_index"`
	ChunkCount      int64          `json:"chunk_count"`
	Status          string         `json:"status"`
	Attempts        int64          `json:"attempts"`
	AvailableAtMs   int64          `json:"available_at_ms"`
	LastError       sql.NullString `json:"last_error"`
	CreatedAtMs     int64          `json:"created_at_ms"`
	SentAtMs        sql.NullInt64  `json:"sent_at_ms"`
}

type Record struct {
	Seq             int64          `json:"seq"`
	ID              string         `json:"id"`
	CommitID        string         `json:"commit_id"`
	ConversationID  sql.NullString `json:"conversation_id"`
	RunID           sql.NullString `json:"run_id"`
	Kind            string         `json:"kind"`
	SchemaVersion   int64          `json:"schema_version"`
	SourceNamespace sql.NullString `json:"source_namespace"`
	SourceEventID   sql.NullString `json:"source_event_id"`
	PayloadJson     string         `json:"payload_json"`
	PayloadSha256   []byte         `json:"payload_sha256"`
	CreatedAtMs     int64          `json:"created_at_ms"`
}

type RecordBlob struct {
	RecordID  string `json:"record_id"`
	PartIndex int64  `json:"part_index"`
	Sha256    []byte `json:"sha256"`
}

type Run struct {
	ID                   string         `json:"id"`
	ConversationID       string         `json:"conversation_id"`
	QueueSeq             int64          `json:"queue_seq"`
	Status               string         `json:"status"`
	Provider             string         `json:"provider"`
	Model                string         `json:"model"`
	ReasoningEffort      sql.NullString `json:"reasoning_effort"`
	SystemPrompt         string         `json:"system_prompt"`
	ConfigJson           sql.NullString `json:"config_json"`
	NextStepSeq          int64          `json:"next_step_seq"`
	ErrorCode            sql.NullString `json:"error_code"`
	ErrorMessage         sql.NullString `json:"error_message"`
	CreatedAtMs          int64          `json:"created_at_ms"`
	StartedAtMs          sql.NullInt64  `json:"started_at_ms"`
	FinishedAtMs         sql.NullInt64  `json:"finished_at_ms"`
	InputNotBeforeMs     sql.NullInt64  `json:"input_not_before_ms"`
	InputRevision        int64          `json:"input_revision"`
	HandledInputRevision int64          `json:"handled_input_revision"`
}
