// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package conversationdb

import (
	"context"
	"database/sql"
)

const acknowledgeRunInput = `-- name: AcknowledgeRunInput :execrows
UPDATE runs
SET handled_input_revision = input_revision, input_not_before_ms = NULL
WHERE id = ? AND status = 'running' AND input_not_before_ms <= ?
`

type AcknowledgeRunInputParams struct {
	ID               string        `json:"id"`
	InputNotBeforeMs sql.NullInt64 `json:"input_not_before_ms"`
}

func (q *Queries) AcknowledgeRunInput(ctx context.Context, arg AcknowledgeRunInputParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acknowledgeRunInput, arg.ID, arg.InputNotBeforeMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceRunInput = `-- name: AdvanceRunInput :one
UPDATE runs
SET input_not_before_ms = CASE
        WHEN status = 'running' AND input_revision = handled_input_revision
            THEN ?1
        ELSE input_not_before_ms
    END,
    input_revision = input_revision + 1
WHERE id = ?2 AND status IN ('queued', 'running')
RETURNING id, conversation_id, queue_seq, status, provider, model, reasoning_effort, system_prompt, config_json, next_step_seq, error_code, error_message, created_at_ms, started_at_ms, finished_at_ms, input_not_before_ms, input_revision, handled_input_revision, session_id
`

type AdvanceRunInputParams struct {
	InputNotBeforeMs sql.NullInt64 `json:"input_not_before_ms"`
	ID               string        `json:"id"`
}

func (q *Queries) AdvanceRunInput(ctx context.Context, arg AdvanceRunInputParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, advanceRunInput, arg.InputNotBeforeMs, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.QueueSeq,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.ReasoningEffort,
		&i.SystemPrompt,
		&i.ConfigJson,
		&i.NextStepSeq,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.InputNotBeforeMs,
		&i.InputRevision,
		&i.HandledInputRevision,
		&i.SessionID,
	)
	return i, err
}

const advanceRunStep = `-- name: AdvanceRunStep :one
UPDATE runs SET next_step_seq = next_step_seq + 1
WHERE id = ? AND status = 'running'
RETURNING next_step_seq - 1 AS step_seq
`

func (q *Queries) AdvanceRunStep(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, advanceRunStep, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const closeSession = `-- name: CloseSession :execrows
UPDATE sessions
SET end_record_id = ?, end_history_seq = ?, ended_at_ms = ?
WHERE id = ? AND conversation_id = ? AND end_record_id IS NULL
`

type CloseSessionParams struct {
	EndRecordID    sql.NullString `json:"end_record_id"`
	EndHistorySeq  sql.NullInt64  `json:"end_history_seq"`
	EndedAtMs      sql.NullInt64  `json:"ended_at_ms"`
	ID             string         `json:"id"`
	ConversationID string         `json:"conversation_id"`
}

func (q *Queries) CloseSession(ctx context.Context, arg CloseSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeSession,
		arg.EndRecordID,
		arg.EndHistorySeq,
		arg.EndedAtMs,
		arg.ID,
		arg.ConversationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const commitMessageToHistory = `-- name: CommitMessageToHistory :execrows
UPDATE messages
SET history_seq = ?, committed_at_ms = ?
WHERE record_id = ? AND history_seq IS NULL
`

type CommitMessageToHistoryParams struct {
	HistorySeq    sql.NullInt64 `json:"history_seq"`
	CommittedAtMs sql.NullInt64 `json:"committed_at_ms"`
	RecordID      string        `json:"record_id"`
}

func (q *Queries) CommitMessageToHistory(ctx context.Context, arg CommitMessageToHistoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, commitMessageToHistory, arg.HistorySeq, arg.CommittedAtMs, arg.RecordID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT s.id, s.conversation_id, s.ordinal, s.start_record_id, s.end_record_id, s.start_history_seq, s.end_history_seq, s.started_at_ms, s.ended_at_ms
FROM sessions s
JOIN conversations c ON c.active_session_id = s.id
WHERE c.id = ?
`

func (q *Queries) GetActiveSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getActiveSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Ordinal,
		&i.StartRecordID,
		&i.EndRecordID,
		&i.StartHistorySeq,
		&i.EndHistorySeq,
		&i.StartedAtMs,
		&i.EndedAtMs,
	)
	return i, err
}

const getContextCommandRecord = `-- name: GetContextCommandRecord :one
SELECT seq, id, commit_id, conversation_id, run_id, kind, schema_version, source_namespace, source_event_id, payload_json, payload_sha256, created_at_ms FROM records
WHERE kind = 'conversation.command.completed' AND source_namespace = ? AND source_event_id = ?
`

type GetContextCommandRecordParams struct {
	SourceNamespace sql.NullString `json:"source_namespace"`
	SourceEventID   sql.NullString `json:"source_event_id"`
}

func (q *Queries) GetContextCommandRecord(ctx context.Context, arg GetContextCommandRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, getContextCommandRecord, arg.SourceNamespace, arg.SourceEventID)
	var i Record
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.CommitID,
		&i.ConversationID,
		&i.RunID,
		&i.Kind,
		&i.SchemaVersion,
		&i.SourceNamespace,
		&i.SourceEventID,
		&i.PayloadJson,
		&i.PayloadSha256,
		&i.CreatedAtMs,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, platform, account_id, external_chat_id, external_thread_id, next_history_seq, created_at_ms, updated_at_ms, active_context_checkpoint_record_id, active_session_id FROM conversations WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.AccountID,
		&i.ExternalChatID,
		&i.ExternalThreadID,
		&i.NextHistorySeq,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
		&i.ActiveContextCheckpointRecordID,
		&i.ActiveSessionID,
	)
	return i, err
}

const getConversationByRoute = `-- name: GetConversationByRoute :one
SELECT id, platform, account_id, external_chat_id, external_thread_id, next_history_seq, created_at_ms, updated_at_ms, active_context_checkpoint_record_id, active_session_id FROM conversations
WHERE platform = ? AND account_id = ? AND external_chat_id = ? AND external_thread_id = ?
`

type GetConversationByRouteParams struct {
	Platform         string `json:"platform"`
	AccountID        string `json:"account_id"`
	ExternalChatID   string `json:"external_chat_id"`
	ExternalThreadID string `json:"external_thread_id"`
}

func (q *Queries) GetConversationByRoute(ctx context.Context, arg GetConversationByRouteParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByRoute,
		arg.Platform,
		arg.AccountID,
		arg.ExternalChatID,
		arg.ExternalThreadID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.AccountID,
		&i.ExternalChatID,
		&i.ExternalThreadID,
		&i.NextHistorySeq,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
		&i.ActiveContextCheckpointRecordID,
		&i.ActiveSessionID,
	)
	return i, err
}

const getIngressRecord = `-- name: GetIngressRecord :one
SELECT seq, id, commit_id, conversation_id, run_id, kind, schema_version, source_namespace, source_event_id, payload_json, payload_sha256, created_at_ms FROM records
WHERE kind = 'ingress.received' AND source_namespace = ? AND source_event_id = ?
`

type GetIngressRecordParams struct {
	SourceNamespace sql.NullString `json:"source_namespace"`
	SourceEventID   sql.NullString `json:"source_event_id"`
}

func (q *Queries) GetIngressRecord(ctx context.Context, arg GetIngressRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, getIngressRecord, arg.SourceNamespace, arg.SourceEventID)
	var i Record
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.CommitID,
		&i.ConversationID,
		&i.RunID,
		&i.Kind,
		&i.SchemaVersion,
		&i.SourceNamespace,
		&i.SourceEventID,
		&i.PayloadJson,
		&i.PayloadSha256,
		&i.CreatedAtMs,
	)
	return i, err
}

const getLatestRunAssistantPayload = `-- name: GetLatestRunAssistantPayload :one
SELECT r.payload_json
FROM messages m
JOIN records r ON r.id = m.record_id
WHERE m.run_id = ? AND m.role = 'assistant' AND m.history_seq IS NOT NULL
ORDER BY m.history_seq DESC
LIMIT 1
`

func (q *Queries) GetLatestRunAssistantPayload(ctx context.Context, runID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestRunAssistantPayload, runID)
	var payload_json string
	err := row.Scan(&payload_json)
	return payload_json, err
}

const getLatestRunUserMessage = `-- name: GetLatestRunUserMessage :one
SELECT m.record_id, m.conversation_id, m.run_id, m.source_record_id, m.role, m.history_seq, m.step_seq, m.step_message_seq, m.committed_at_ms
FROM messages m
JOIN records r ON r.id = m.record_id
WHERE m.run_id = ? AND m.role = 'user'
ORDER BY r.seq DESC
LIMIT 1
`

func (q *Queries) GetLatestRunUserMessage(ctx context.Context, runID string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getLatestRunUserMessage, runID)
	var i Message
	err := row.Scan(
		&i.RecordID,
		&i.ConversationID,
		&i.RunID,
		&i.SourceRecordID,
		&i.Role,
		&i.HistorySeq,
		&i.StepSeq,
		&i.StepMessageSeq,
		&i.CommittedAtMs,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT record_id, conversation_id, run_id, source_record_id, role, history_seq, step_seq, step_message_seq, committed_at_ms FROM messages WHERE record_id = ?
`

func (q *Queries) GetMessage(ctx context.Context, recordID string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, recordID)
	var i Message
	err := row.Scan(
		&i.RecordID,
		&i.ConversationID,
		&i.RunID,
		&i.SourceRecordID,
		&i.Role,
		&i.HistorySeq,
		&i.StepSeq,
		&i.StepMessageSeq,
		&i.CommittedAtMs,
	)
	return i, err
}

const getMessageBySourceRecord = `-- name: GetMessageBySourceRecord :one
SELECT record_id, conversation_id, run_id, source_record_id, role, history_seq, step_seq, step_message_seq, committed_at_ms FROM messages WHERE source_record_id = ?
`

func (q *Queries) GetMessageBySourceRecord(ctx context.Context, sourceRecordID sql.NullString) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageBySourceRecord, sourceRecordID)
	var i Message
	err := row.Scan(
		&i.RecordID,
		&i.ConversationID,
		&i.RunID,
		&i.SourceRecordID,
		&i.Role,
		&i.HistorySeq,
		&i.StepSeq,
		&i.StepMessageSeq,
		&i.CommittedAtMs,
	)
	return i, err
}

const getNextQueuedRun = `-- name: GetNextQueuedRun :one
SELECT id, conversation_id, queue_seq, status, provider, model, reasoning_effort, system_prompt, config_json, next_step_seq, error_code, error_message, created_at_ms, started_at_ms, finished_at_ms, input_not_before_ms, input_revision, handled_input_revision, session_id FROM runs WHERE status = 'queued' ORDER BY queue_seq LIMIT 1
`

func (q *Queries) GetNextQueuedRun(ctx context.Context) (Run, error) {
	row := q.db.QueryRowContext(ctx, getNextQueuedRun)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.QueueSeq,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.ReasoningEffort,
		&i.SystemPrompt,
		&i.ConfigJson,
		&i.NextStepSeq,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.InputNotBeforeMs,
		&i.InputRevision,
		&i.HandledInputRevision,
		&i.SessionID,
	)
	return i, err
}

const getOpenRun = `-- name: GetOpenRun :one
SELECT id, conversation_id, queue_seq, status, provider, model, reasoning_effort, system_prompt, config_json, next_step_seq, error_code, error_message, created_at_ms, started_at_ms, finished_at_ms, input_not_before_ms, input_revision, handled_input_revision, session_id FROM runs
WHERE conversation_id = ? AND status IN ('queued', 'running')
LIMIT 1
`

func (q *Queries) GetOpenRun(ctx context.Context, conversationID string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getOpenRun, conversationID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.QueueSeq,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.ReasoningEffort,
		&i.SystemPrompt,
		&i.ConfigJson,
		&i.NextStepSeq,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.InputNotBeforeMs,
		&i.InputRevision,
		&i.HandledInputRevision,
		&i.SessionID,
	)
	return i, err
}

const getOutbox = `-- name: GetOutbox :one
SELECT o.id, o.record_id, o.enqueue_seq, o.conversation_id, o.run_id, o.message_record_id, o.reply_to_record_id, o.kind, o.chunk_index, o.chunk_count, o.status, o.attempts, o.available_at_ms, o.last_error, o.created_at_ms, o.sent_at_ms, r.payload_json, r.schema_version
FROM outbox o
JOIN records r ON r.id = o.record_id
WHERE o.id = ?
`

type GetOutboxRow struct {
	ID              string         `json:"id"`
	RecordID        string         `json:"record_id"`
	EnqueueSeq      int64          `json:"enqueue_seq"`
	ConversationID  string         `json:"conversation_id"`
	RunID           sql.NullString `json:"run_id"`
	MessageRecordID sql.NullString `json:"message_record_id"`
	ReplyToRecordID sql.NullString `json:"reply_to_record_id"`
	Kind            string         `json:"kind"`
	ChunkIndex      int64          `json:"chunk_index"`
	ChunkCount      int64          `json:"chunk_count"`
	Status          string         `json:"status"`
	Attempts        int64          `json:"attempts"`
	AvailableAtMs   int64          `json:"available_at_ms"`
	LastError       sql.NullString `json:"last_error"`
	CreatedAtMs     int64          `json:"created_at_ms"`
	SentAtMs        sql.NullInt64  `json:"sent_at_ms"`
	PayloadJson     string         `json:"payload_json"`
	SchemaVersion   int64          `json:"schema_version"`
}

func (q *Queries) GetOutbox(ctx context.Context, id string) (GetOutboxRow, error) {
	row := q.db.QueryRowContext(ctx, getOutbox, id)
	var i GetOutboxRow
	err := row.Scan(
		&i.ID,
		&i.RecordID,
		&i.EnqueueSeq,
		&i.ConversationID,
		&i.RunID,
		&i.MessageRecordID,
		&i.ReplyToRecordID,
		&i.Kind,
		&i.ChunkIndex,
		&i.ChunkCount,
		&i.Status,
		&i.Attempts,
		&i.AvailableAtMs,
		&i.LastError,
		&i.CreatedAtMs,
		&i.SentAtMs,
		&i.PayloadJson,
		&i.SchemaVersion,
	)
	return i, err
}

const getRecord = `-- name: GetRecord :one
SELECT seq, id, commit_id, conversation_id, run_id, kind, schema_version, source_namespace, source_event_id, payload_json, payload_sha256, created_at_ms FROM records WHERE id = ?
`

func (q *Queries) GetRecord(ctx context.Context, id string) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecord, id)
	var i Record
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.CommitID,
		&i.ConversationID,
		&i.RunID,
		&i.Kind,
		&i.SchemaVersion,
		&i.SourceNamespace,
		&i.SourceEventID,
		&i.PayloadJson,
		&i.PayloadSha256,
		&i.CreatedAtMs,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, conversation_id, queue_seq, status, provider, model, reasoning_effort, system_prompt, config_json, next_step_seq, error_code, error_message, created_at_ms, started_at_ms, finished_at_ms, input_not_before_ms, input_revision, handled_input_revision, session_id FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.QueueSeq,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.ReasoningEffort,
		&i.SystemPrompt,
		&i.ConfigJson,
		&i.NextStepSeq,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.InputNotBeforeMs,
		&i.InputRevision,
		&i.HandledInputRevision,
		&i.SessionID,
	)
	return i, err
}

const getRunningRun = `-- name: GetRunningRun :one
SELECT id, conversation_id, queue_seq, status, provider, model, reasoning_effort, system_prompt, config_json, next_step_seq, error_code, error_message, created_at_ms, started_at_ms, finished_at_ms, input_not_before_ms, input_revision, handled_input_revision, session_id FROM runs WHERE status = 'running' LIMIT 1
`

func (q *Queries) GetRunningRun(ctx context.Context) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunningRun)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.QueueSeq,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.ReasoningEffort,
		&i.SystemPrompt,
		&i.ConfigJson,
		&i.NextStepSeq,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.InputNotBeforeMs,
		&i.InputRevision,
		&i.HandledInputRevision,
		&i.SessionID,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, conversation_id, ordinal, start_record_id, end_record_id, start_history_seq, end_history_seq, started_at_ms, ended_at_ms FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Ordinal,
		&i.StartRecordID,
		&i.EndRecordID,
		&i.StartHistorySeq,
		&i.EndHistorySeq,
		&i.StartedAtMs,
		&i.EndedAtMs,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (
    record_id, conversation_id, run_id, source_record_id, role,
    history_seq, step_seq, step_message_seq, committed_at_ms
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	RecordID       string         `json:"record_id"`
	ConversationID string         `json:"conversation_id"`
	RunID          string         `json:"run_id"`
	SourceRecordID sql.NullString `json:"source_record_id"`
	Role           string         `json:"role"`
	HistorySeq     sql.NullInt64  `json:"history_seq"`
	StepSeq        sql.NullInt64  `json:"step_seq"`
	StepMessageSeq sql.NullInt64  `json:"step_message_seq"`
	CommittedAtMs  sql.NullInt64  `json:"committed_at_ms"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.RecordID,
		arg.ConversationID,
		arg.RunID,
		arg.SourceRecordID,
		arg.Role,
		arg.HistorySeq,
		arg.StepSeq,
		arg.StepMessageSeq,
		arg.CommittedAtMs,
	)
	return err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (
    id, record_id, enqueue_seq, conversation_id, run_id, message_record_id, reply_to_record_id,
    kind, chunk_index, chunk_count, status, attempts, available_at_ms, created_at_ms
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', 0, ?, ?)
`

type InsertOutboxParams struct {
	ID              string         `json:"id"`
	RecordID        string         `json:"record_id"`
	EnqueueSeq      int64          `json:"enqueue_seq"`
	ConversationID  string         `json:"conversation_id"`
	RunID           sql.NullString `json:"run_id"`
	MessageRecordID sql.NullString `json:"message_record_id"`
	ReplyToRecordID sql.NullString `json:"reply_to_record_id"`
	Kind            string         `json:"kind"`
	ChunkIndex      int64          `json:"chunk_index"`
	ChunkCount      int64          `json:"chunk_count"`
	AvailableAtMs   int64          `json:"available_at_ms"`
	CreatedAtMs     int64          `json:"created_at_ms"`
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.ExecContext(ctx, insertOutbox,
		arg.ID,
		arg.RecordID,
		arg.EnqueueSeq,
		arg.ConversationID,
		arg.RunID,
		arg.MessageRecordID,
		arg.ReplyToRecordID,
		arg.Kind,
		arg.ChunkIndex,
		arg.ChunkCount,
		arg.AvailableAtMs,
		arg.CreatedAtMs,
	)
	return err
}

const insertRecord = `-- name: InsertRecord :one
INSERT INTO records (
    id, commit_id, conversation_id, run_id, kind, schema_version,
    source_namespace, source_event_id, payload_json, payload_sha256, created_at_ms
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING seq
`

type InsertRecordParams struct {
	ID              string         `json:"id"`
	CommitID        string         `json:"commit_id"`
	ConversationID  sql.NullString `json:"conversation_id"`
	RunID           sql.NullString `json:"run_id"`
	Kind            string         `json:"kind"`
	SchemaVersion   int64          `json:"schema_version"`
	SourceNamespace sql.NullString `json:"source_namespace"`
	SourceEventID   sql.NullString `json:"source_event_id"`
	PayloadJson     string         `json:"payload_json"`
	PayloadSha256   []byte         `json:"payload_sha256"`
	CreatedAtMs     int64          `json:"created_at_ms"`
}

func (q *Queries) InsertRecord(ctx context.Context, arg InsertRecordParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRecord,
		arg.ID,
		arg.CommitID,
		arg.ConversationID,
		arg.RunID,
		arg.Kind,
		arg.SchemaVersion,
		arg.SourceNamespace,
		arg.SourceEventID,
		arg.PayloadJson,
		arg.PayloadSha256,
		arg.CreatedAtMs,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const insertRun = `-- name: InsertRun :exec
INSERT INTO runs (
    id, conversation_id, session_id, queue_seq, status, provider, model, reasoning_effort,
    system_prompt, config_json, next_step_seq, created_at_ms,
    input_not_before_ms, input_revision, handled_input_revision
) VALUES (?, ?, ?, ?, 'queued', ?, ?, ?, ?, ?, 0, ?, ?, 0, 0)
`

type InsertRunParams struct {
	ID               string         `json:"id"`
	ConversationID   string         `json:"conversation_id"`
	SessionID        sql.NullString `json:"session_id"`
	QueueSeq         int64          `json:"queue_seq"`
	Provider         string         `json:"provider"`
	Model            string         `json:"model"`
	ReasoningEffort  sql.NullString `json:"reasoning_effort"`
	SystemPrompt     string         `json:"system_prompt"`
	ConfigJson       sql.NullString `json:"config_json"`
	CreatedAtMs      int64          `json:"created_at_ms"`
	InputNotBeforeMs sql.NullInt64  `json:"input_not_before_ms"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) error {
	_, err := q.db.ExecContext(ctx, insertRun,
		arg.ID,
		arg.ConversationID,
		arg.SessionID,
		arg.QueueSeq,
		arg.Provider,
		arg.Model,
		arg.ReasoningEffort,
		arg.SystemPrompt,
		arg.ConfigJson,
		arg.CreatedAtMs,
		arg.InputNotBeforeMs,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (
    id, conversation_id, ordinal, start_record_id, start_history_seq, started_at_ms
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	ID              string `json:"id"`
	ConversationID  string `json:"conversation_id"`
	Ordinal         int64  `json:"ordinal"`
	StartRecordID   string `json:"start_record_id"`
	StartHistorySeq int64  `json:"start_history_seq"`
	StartedAtMs     int64  `json:"started_at_ms"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.ConversationID,
		arg.Ordinal,
		arg.StartRecordID,
		arg.StartHistorySeq,
		arg.StartedAtMs,
	)
	return err
}

const interruptRunningRuns = `-- name: InterruptRunningRuns :many
UPDATE runs
SET status = 'interrupted', error_code = 'process_restart',
    error_message = 'agent process stopped before the run completed', finished_at_ms = ?
WHERE status = 'running'
RETURNING id, conversation_id, queue_seq, status, provider, model, reasoning_effort, system_prompt, config_json, next_step_seq, error_code, error_message, created_at_ms, started_at_ms, finished_at_ms, input_not_before_ms, input_revision, handled_input_revision, session_id
`

func (q *Queries) InterruptRunningRuns(ctx context.Context, finishedAtMs sql.NullInt64) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, interruptRunningRuns, finishedAtMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.QueueSeq,
			&i.Status,
			&i.Provider,
			&i.Model,
			&i.ReasoningEffort,
			&i.SystemPrompt,
			&i.ConfigJson,
			&i.NextStepSeq,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAtMs,
			&i.StartedAtMs,
			&i.FinishedAtMs,
			&i.InputNotBeforeMs,
			&i.InputRevision,
			&i.HandledInputRevision,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationHistory = `-- name: ListConversationHistory :many
SELECT r.payload_json, r.schema_version, m.record_id, m.conversation_id, m.run_id, m.source_record_id, m.role, m.history_seq, m.step_seq, m.step_message_seq, m.committed_at_ms
FROM messages m
JOIN records r ON r.id = m.record_id
WHERE m.conversation_id = ? AND m.history_seq IS NOT NULL
ORDER BY m.history_seq
`

type ListConversationHistoryRow struct {
	PayloadJson    string         `json:"payload_json"`
	SchemaVersion  int64          `json:"schema_version"`
	RecordID       string         `json:"record_id"`
	ConversationID string         `json:"conversation_id"`
	RunID          string         `json:"run_id"`
	SourceRecordID sql.NullString `json:"source_record_id"`
	Role           string         `json:"role"`
	HistorySeq     sql.NullInt64  `json:"history_seq"`
	StepSeq        sql.NullInt64  `json:"step_seq"`
	StepMessageSeq sql.NullInt64  `json:"step_message_seq"`
	CommittedAtMs  sql.NullInt64  `json:"committed_at_ms"`
}

func (q *Queries) ListConversationHistory(ctx context.Context, conversationID string) ([]ListConversationHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationHistory, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationHistoryRow{}
	for rows.Next() {
		var i ListConversationHistoryRow
		if err := rows.Scan(
			&i.PayloadJson,
			&i.SchemaVersion,
			&i.RecordID,
			&i.ConversationID,
			&i.RunID,
			&i.SourceRecordID,
			&i.Role,
			&i.HistorySeq,
			&i.StepSeq,
			&i.StepMessageSeq,
			&i.CommittedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationHistoryAfter = `-- name: ListConversationHistoryAfter :many
SELECT r.payload_json, r.schema_version, m.record_id, m.conversation_id, m.run_id, m.source_record_id, m.role, m.history_seq, m.step_seq, m.step_message_seq, m.committed_at_ms
FROM messages m
JOIN records r ON r.id = m.record_id
WHERE m.conversation_id = ? AND m.history_seq > ?
ORDER BY m.history_seq
`

type ListConversationHistoryAfterParams struct {
	ConversationID string        `json:"conversation_id"`
	HistorySeq     sql.NullInt64 `json:"history_seq"`
}

type ListConversationHistoryAfterRow struct {
	PayloadJson    string         `json:"payload_json"`
	SchemaVersion  int64          `json:"schema_version"`
	RecordID       string         `json:"record_id"`
	ConversationID string         `json:"conversation_id"`
	RunID          string         `json:"run_id"`
	SourceRecordID sql.NullString `json:"source_record_id"`
	Role           string         `json:"role"`
	HistorySeq     sql.NullInt64  `json:"history_seq"`
	StepSeq        sql.NullInt64  `json:"step_seq"`
	StepMessageSeq sql.NullInt64  `json:"step_message_seq"`
	CommittedAtMs  sql.NullInt64  `json:"committed_at_ms"`
}

func (q *Queries) ListConversationHistoryAfter(ctx context.Context, arg ListConversationHistoryAfterParams) ([]ListConversationHistoryAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationHistoryAfter, arg.ConversationID, arg.HistorySeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationHistoryAfterRow{}
	for rows.Next() {
		var i ListConversationHistoryAfterRow
		if err := rows.Scan(
			&i.PayloadJson,
			&i.SchemaVersion,
			&i.RecordID,
			&i.ConversationID,
			&i.RunID,
			&i.SourceRecordID,
			&i.Role,
			&i.HistorySeq,
			&i.StepSeq,
			&i.StepMessageSeq,
			&i.CommittedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOutboxHeads = `-- name: ListPendingOutboxHeads :many
SELECT o.id, o.record_id, o.enqueue_seq, o.conversation_id, o.run_id, o.message_record_id, o.reply_to_record_id, o.kind, o.chunk_index, o.chunk_count, o.status, o.attempts, o.available_at_ms, o.last_error, o.created_at_ms, o.sent_at_ms, r.payload_json, r.schema_version
FROM outbox o
JOIN records r ON r.id = o.record_id
WHERE o.status = 'pending'
  AND o.available_at_ms <= ?
  AND o.id = (
      SELECT o2.id FROM outbox o2
      WHERE o2.conversation_id = o.conversation_id
        AND o2.status NOT IN ('sent', 'dead')
      ORDER BY o2.enqueue_seq
      LIMIT 1
  )
ORDER BY o.enqueue_seq
`

type ListPendingOutboxHeadsRow struct {
	ID              string         `json:"id"`
	RecordID        string         `json:"record_id"`
	EnqueueSeq      int64          `json:"enqueue_seq"`
	ConversationID  string         `json:"conversation_id"`
	RunID           sql.NullString `json:"run_id"`
	MessageRecordID sql.NullString `json:"message_record_id"`
	ReplyToRecordID sql.NullString `json:"reply_to_record_id"`
	Kind            string         `json:"kind"`
	ChunkIndex      int64          `json:"chunk_index"`
	ChunkCount      int64          `json:"chunk_count"`
	Status          string         `json:"status"`
	Attempts        int64          `json:"attempts"`
	AvailableAtMs   int64          `json:"available_at_ms"`
	LastError       sql.NullString `json:"last_error"`
	CreatedAtMs     int64          `json:"created_at_ms"`
	SentAtMs        sql.NullInt64  `json:"sent_at_ms"`
	PayloadJson     string         `json:"payload_json"`
	SchemaVersion   int64          `json:"schema_version"`
}

func (q *Queries) ListPendingOutboxHeads(ctx context.Context, availableAtMs int64) ([]ListPendingOutboxHeadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOutboxHeads, availableAtMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingOutboxHeadsRow{}
	for rows.Next() {
		var i ListPendingOutboxHeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordID,
			&i.EnqueueSeq,
			&i.ConversationID,
			&i.RunID,
			&i.MessageRecordID,
			&i.ReplyToRecordID,
			&i.Kind,
			&i.ChunkIndex,
			&i.ChunkCount,
			&i.Status,
			&i.Attempts,
			&i.AvailableAtMs,
			&i.LastError,
			&i.CreatedAtMs,
			&i.SentAtMs,
			&i.PayloadJson,
			&i.SchemaVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRunMessages = `-- name: ListPendingRunMessages :many
SELECT r.payload_json, r.schema_version, m.record_id, m.conversation_id, m.run_id, m.source_record_id, m.role, m.history_seq, m.step_seq, m.step_message_seq, m.committed_at_ms
FROM messages m
JOIN records r ON r.id = m.record_id
WHERE m.run_id = ? AND m.history_seq IS NULL
ORDER BY r.seq
`

type ListPendingRunMessagesRow struct {
	PayloadJson    string         `json:"payload_json"`
	SchemaVersion  int64          `json:"schema_version"`
	RecordID       string         `json:"record_id"`
	ConversationID string         `json:"conversation_id"`
	RunID          string         `json:"run_id"`
	SourceRecordID sql.NullString `json:"source_record_id"`
	Role           string         `json:"role"`
	HistorySeq     sql.NullInt64  `json:"history_seq"`
	StepSeq        sql.NullInt64  `json:"step_seq"`
	StepMessageSeq sql.NullInt64  `json:"step_message_seq"`
	CommittedAtMs  sql.NullInt64  `json:"committed_at_ms"`
}

func (q *Queries) ListPendingRunMessages(ctx context.Context, runID string) ([]ListPendingRunMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingRunMessages, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingRunMessagesRow{}
	for rows.Next() {
		var i ListPendingRunMessagesRow
		if err := rows.Scan(
			&i.PayloadJson,
			&i.SchemaVersion,
			&i.RecordID,
			&i.ConversationID,
			&i.RunID,
			&i.SourceRecordID,
			&i.Role,
			&i.HistorySeq,
			&i.StepSeq,
			&i.StepMessageSeq,
			&i.CommittedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecords = `-- name: ListRecords :many
SELECT seq, id, commit_id, conversation_id, run_id, kind, schema_version, source_namespace, source_event_id, payload_json, payload_sha256, created_at_ms FROM records ORDER BY seq
`

func (q *Queries) ListRecords(ctx context.Context) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.CommitID,
			&i.ConversationID,
			&i.RunID,
			&i.Kind,
			&i.SchemaVersion,
			&i.SourceNamespace,
			&i.SourceEventID,
			&i.PayloadJson,
			&i.PayloadSha256,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionAssistantPayloads = `-- name: ListSessionAssistantPayloads :many
SELECT r.payload_json, r.schema_version
FROM messages m
JOIN records r ON r.id = m.record_id
JOIN sessions s ON s.id = ?1
WHERE m.conversation_id = ?2
  AND s.conversation_id = m.conversation_id
  AND m.role = 'assistant'
  AND m.history_seq IS NOT NULL
  AND m.history_seq >= s.start_history_seq
  AND (s.end_history_seq IS NULL OR m.history_seq <= s.end_history_seq)
`

type ListSessionAssistantPayloadsParams struct {
	SessionID      string `json:"session_id"`
	ConversationID string `json:"conversation_id"`
}

type ListSessionAssistantPayloadsRow struct {
	PayloadJson   string `json:"payload_json"`
	SchemaVersion int64  `json:"schema_version"`
}

func (q *Queries) ListSessionAssistantPayloads(ctx context.Context, arg ListSessionAssistantPayloadsParams) ([]ListSessionAssistantPayloadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionAssistantPayloads, arg.SessionID, arg.ConversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionAssistantPayloadsRow{}
	for rows.Next() {
		var i ListSessionAssistantPayloadsRow
		if err := rows.Scan(&i.PayloadJson, &i.SchemaVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionCheckpointPayloads = `-- name: ListSessionCheckpointPayloads :many
SELECT r.payload_json, r.schema_version
FROM records r
JOIN sessions s ON s.id = ?1
WHERE r.conversation_id = ?2
  AND s.conversation_id = r.conversation_id
  AND r.kind = 'context.checkpoint.created'
  AND json_extract(r.payload_json, '$.sessionId') = s.id
`

type ListSessionCheckpointPayloadsParams struct {
	SessionID      string         `json:"session_id"`
	ConversationID sql.NullString `json:"conversation_id"`
}

type ListSessionCheckpointPayloadsRow struct {
	PayloadJson   string `json:"payload_json"`
	SchemaVersion int64  `json:"schema_version"`
}

func (q *Queries) ListSessionCheckpointPayloads(ctx context.Context, arg ListSessionCheckpointPayloadsParams) ([]ListSessionCheckpointPayloadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionCheckpointPayloads, arg.SessionID, arg.ConversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionCheckpointPayloadsRow{}
	for rows.Next() {
		var i ListSessionCheckpointPayloadsRow
		if err := rows.Scan(&i.PayloadJson, &i.SchemaVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxAttempt = `-- name: MarkOutboxAttempt :execrows
UPDATE outbox SET attempts = attempts + 1, last_error = NULL WHERE id = ? AND status = 'pending'
`

func (q *Queries) MarkOutboxAttempt(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxAttempt, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOutboxDead = `-- name: MarkOutboxDead :execrows
UPDATE outbox SET status = 'dead', last_error = ? WHERE id = ? AND status = 'pending'
`

type MarkOutboxDeadParams struct {
	LastError sql.NullString `json:"last_error"`
	ID        string         `json:"id"`
}

func (q *Queries) MarkOutboxDead(ctx context.Context, arg MarkOutboxDeadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxDead, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOutboxSent = `-- name: MarkOutboxSent :execrows
UPDATE outbox SET status = 'sent', sent_at_ms = ?, last_error = NULL WHERE id = ? AND status = 'pending'
`

type MarkOutboxSentParams struct {
	SentAtMs sql.NullInt64 `json:"sent_at_ms"`
	ID       string        `json:"id"`
}

func (q *Queries) MarkOutboxSent(ctx context.Context, arg MarkOutboxSentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxSent, arg.SentAtMs, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rescheduleOutbox = `-- name: RescheduleOutbox :execrows
UPDATE outbox SET available_at_ms = ?, last_error = ? WHERE id = ? AND status = 'pending'
`

type RescheduleOutboxParams struct {
	AvailableAtMs int64          `json:"available_at_ms"`
	LastError     sql.NullString `json:"last_error"`
	ID            string         `json:"id"`
}

func (q *Queries) RescheduleOutbox(ctx context.Context, arg RescheduleOutboxParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rescheduleOutbox, arg.AvailableAtMs, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reserveHistoryRange = `-- name: ReserveHistoryRange :one
UPDATE conversations
SET next_history_seq = next_history_seq + ?1, updated_at_ms = ?2
WHERE id = ?3
RETURNING next_history_seq - ?1 AS first_history_seq
`

type ReserveHistoryRangeParams struct {
	Count          int64  `json:"count"`
	UpdatedAtMs    int64  `json:"updated_at_ms"`
	ConversationID string `json:"conversation_id"`
}

func (q *Queries) ReserveHistoryRange(ctx context.Context, arg ReserveHistoryRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, reserveHistoryRange, arg.Count, arg.UpdatedAtMs, arg.ConversationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setActiveContextCheckpoint = `-- name: SetActiveContextCheckpoint :execrows
UPDATE conversations
SET active_context_checkpoint_record_id = ?1,
    updated_at_ms = ?2
WHERE id = ?3
  AND next_history_seq - 1 = ?4
  AND COALESCE(active_context_checkpoint_record_id, '') = ?5
`

type SetActiveContextCheckpointParams struct {
	RecordID          sql.NullString `json:"record_id"`
	UpdatedAtMs       int64          `json:"updated_at_ms"`
	ConversationID    string         `json:"conversation_id"`
	HistoryThroughSeq int64          `json:"history_through_seq"`
	ParentRecordID    sql.NullString `json:"parent_record_id"`
}

func (q *Queries) SetActiveContextCheckpoint(ctx context.Context, arg SetActiveContextCheckpointParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setActiveContextCheckpoint,
		arg.RecordID,
		arg.UpdatedAtMs,
		arg.ConversationID,
		arg.HistoryThroughSeq,
		arg.ParentRecordID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setActiveSession = `-- name: SetActiveSession :execrows
UPDATE conversations
SET active_session_id = ?1, updated_at_ms = ?2
WHERE id = ?3
  AND COALESCE(active_session_id, '') = ?4
`

type SetActiveSessionParams struct {
	SessionID         sql.NullString `json:"session_id"`
	UpdatedAtMs       int64          `json:"updated_at_ms"`
	ConversationID    string         `json:"conversation_id"`
	PreviousSessionID sql.NullString `json:"previous_session_id"`
}

func (q *Queries) SetActiveSession(ctx context.Context, arg SetActiveSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setActiveSession,
		arg.SessionID,
		arg.UpdatedAtMs,
		arg.ConversationID,
		arg.PreviousSessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRunTerminal = `-- name: SetRunTerminal :execrows
UPDATE runs
SET status = ?, error_code = ?, error_message = ?, finished_at_ms = ?
WHERE id = ? AND status = 'running'
`

type SetRunTerminalParams struct {
	Status       string         `json:"status"`
	ErrorCode    sql.NullString `json:"error_code"`
	ErrorMessage sql.NullString `json:"error_message"`
	FinishedAtMs sql.NullInt64  `json:"finished_at_ms"`
	ID           string         `json:"id"`
}

func (q *Queries) SetRunTerminal(ctx context.Context, arg SetRunTerminalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRunTerminal,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.FinishedAtMs,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startRun = `-- name: StartRun :execrows
UPDATE runs
SET status = 'running', started_at_ms = ?,
    handled_input_revision = input_revision, input_not_before_ms = NULL
WHERE id = ? AND status = 'queued'
`

type StartRunParams struct {
	StartedAtMs sql.NullInt64 `json:"started_at_ms"`
	ID          string        `json:"id"`
}

func (q *Queries) StartRun(ctx context.Context, arg StartRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startRun, arg.StartedAtMs, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertConversation = `-- name: UpsertConversation :one
INSERT INTO conversations (
    id, platform, account_id, external_chat_id, external_thread_id,
    next_history_seq, created_at_ms, updated_at_ms
) VALUES (?, ?, ?, ?, ?, 1, ?, ?)
ON CONFLICT (platform, account_id, external_chat_id, external_thread_id)
DO UPDATE SET updated_at_ms = excluded.updated_at_ms
RETURNING id, platform, account_id, external_chat_id, external_thread_id, next_history_seq, created_at_ms, updated_at_ms, active_context_checkpoint_record_id, active_session_id
`

type UpsertConversationParams struct {
	ID               string `json:"id"`
	Platform         string `json:"platform"`
	AccountID        string `json:"account_id"`
	ExternalChatID   string `json:"external_chat_id"`
	ExternalThreadID string `json:"external_thread_id"`
	CreatedAtMs      int64  `json:"created_at_ms"`
	UpdatedAtMs      int64  `json:"updated_at_ms"`
}

func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, upsertConversation,
		arg.ID,
		arg.Platform,
		arg.AccountID,
		arg.ExternalChatID,
		arg.ExternalThreadID,
		arg.CreatedAtMs,
		arg.UpdatedAtMs,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.AccountID,
		&i.ExternalChatID,
		&i.ExternalThreadID,
		&i.NextHistorySeq,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
		&i.ActiveContextCheckpointRecordID,
		&i.ActiveSessionID,
	)
	return i, err
}
